### ISSUE TITLE
Please add the ability to hide the video.

### ISSUE THREAD

**Issue by Reanmachine** [swimmadude66/YTRadio#15]
Just hide it visibly with a toggle somewhere.

**Comment by localyost3000** [comment]
gotta avoid violating youtube ToS, but i think streaming the video to a hidden div is ok so long as it isnt default.

**Comment by Reanmachine** [comment]
I'd be ok writing a TampermonkeyScript to toggle this if you dont want to violate the TOS. I wish we could just hide the video stream but keep the player visible so the "ads" show and YT doesn't get anal.

**Comment by localyost3000** [comment]
Hiding the video portion of an embedded stream violates YT ToS. Even though I have a handy div around just the video that doesnt affect the page layout if you were to hide it. I mean, its as simple as `$('#screen').hide()`, but sadly I cannot legally enable it by default, or encourage you to use any sort of js/jquery command to hide the stream.
