### ISSUE TITLE
Show video(song) length in the results.

### ISSUE THREAD

**Issue by Reanmachine** [swimmadude66/YTRadio#17]
This will let us filter down which link is best.

**Comment by localyost3000** [comment]
Funny story, That is a separate API call, so I've been deferring duration lookup to queue time. I could be persuaded to change that stance however.

**Comment by Reanmachine** [comment]
This is why:

![Example](http://i.imgur.com/dT27s3o.png)

**Comment by localyost3000** [comment]
Solved in Beta 0.1.5
