### ISSUE TITLE
Song History

### ISSUE THREAD

**Issue by Sveini** [swimmadude66/YTRadio#18]
The songs stay in queue after they are played, so you have to remove them yourselves. So can you make a "history" list which the songs that are finished gets moved to. Just like in plug.

**Comment by localyost3000** [comment]
I am not seeing the behavior you've described. Instead, I see the queue being popped and repoplated with the next song in the DJ's playlist.

On the matter of history, a schema exists and the feature is planned, but is currently slated for Beta 0.2.0 after the voting system is implemented.

**Comment by localyost3000** [comment]
This has been assigned an enhancement label for the history idea and will be re-titled as such.

**Comment by localyost3000** [comment]
Implemented in Beta 0.3.0
