### ISSUE TITLE
Volume resets on each new song.

### ISSUE THREAD

**Issue by Reanmachine** [swimmadude66/YTRadio#19]
# Chrome 45.0.2454.101 m

**Reproduction Steps**
1. Change your volume while a song is playing
2. Observe the change in volume (make sure it's something noticable)
3. Wait for song to change

**Expected:**

Next song gets the same volume value as the previous

**Actual:**

Volume is maximum again.

**Comment by JefferysTuber** [comment]
Chrome Version 45.0.2454.101 m

I'm running same version, and do NOT have the same issue.

EDIT:Upon review, I actually do have the same issue as Rean.

**Comment by Reanmachine** [comment]
To be clear, the volume goes up but the slider does not. As soon as I click the slider the volume snaps abruptly to where it should be.

**Comment by JefferysTuber** [comment]
Upon review, I actually do have the same issue as Rean.

**Comment by localyost3000** [comment]
Just in case, I re-set volume the same way mute is set on each new play.

This should allow volume to carry over.

**Comment by JefferysTuber** [comment]
Well, the volume level is persistent - but the UI element, the volume slider, seems to reset... eventually.

Not a huge issue though, and it seems to take more than 1 song before it resets.
