### ISSUE TITLE
Playlists not persistant

### ISSUE THREAD

**Issue by JefferysTuber** [swimmadude66/YTRadio#22]
I've had to start a playlist from scratch each day so far, Its getting a bit old.

Doesn't seem to be tied to browser reloads, maybe the playlists are being dropped everytime you do a release or other backend update?

**Comment by JefferysTuber** [comment]
Not sure if changes are being made currently, but my playlist just disappeared. While I was in queue.

**Comment by localyost3000** [comment]
Fixed the issue. Funny enough the data was never actually lost until a rebuild was attempted.

The fetch_playlists method never fired again after login, so it was attempting to load a playlist for a logged out user. However if you did not refresh after logging in, and tried to add anything new... it overwrote the playlist.

This fix will be pushed in Beta 0.2.0 this week (hopefully tonight)
