### ISSUE TITLE
Tracks not advancing until browser tab has focus

### ISSUE THREAD

**Issue by JefferysTuber** [swimmadude66/YTRadio#26]
Browser/Desktop details as requested:

Win 10, Chrome 46.0.2490.71 m

User Agent:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36

Browser Plugin Details:
Plugin 0: Chrome PDF Viewer; ; mhjfbmdgcfjbbpaeojofohoefgiehjai; (; application/pdf; pdf). Plugin 1: Chrome PDF Viewer; Portable Document Format; internal-pdf-viewer; (Portable Document Format; application/x-google-chrome-pdf; pdf). Plugin 2: Native Client; ; internal-nacl-plugin; (Native Client Executable; application/x-nacl; ) (Portable Native Client Executable; application/x-pnacl; ). Plugin 3: Shockwave Flash; Shockwave Flash 19.0 r0; pepflashplayer.dll; (Shockwave Flash; application/x-shockwave-flash; swf) (Shockwave Flash; application/futuresplash; spl). Plugin 4: Widevine Content Decryption Module; Enables Widevine licenses for playback of HTML audio/video content. (version: 1.4.8.824); widevinecdmadapter.dll; (Widevine Content Decryption Module; application/x-ppapi-widevine-cdm; ).

Console output:

Failed to load resource: net::ERR_FAILED
https://static.doubleclick.net/instream/ad_status.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED
radiocontroller.js:117 sent song-end
chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED
https://static.doubleclick.net/instream/ad_status.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED
2angular.min.js:107 TypeError: $scope.ytplayer.getCurrentTime is not a function
    at radiocontroller.js:88
    at angular.min.js:121
    at n.$eval (angular.min.js:133)
    at n.$digest (angular.min.js:130)
    at n.$apply (angular.min.js:133)
    at angular.min.js:97(anonymous function) @ angular.min.js:107
https://googleads.g.doubleclick.net/pagead/ads?sdkv=h.3.0.0&sdki=8000405&vi…BlzmDUsTXBBNCV3-nGEmf7j2xxymfF89RPr4pww&ref=https%3A%2F%2Fswimmadev.xyz%2F Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://pagead2.googlesyndication.com/pagead/gen_204?rt=adsense&lid=17&id&c=1708006551060480&domain=swimmadev.xyz Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://googleads.g.doubleclick.net/pagead/ads?sdkv=h.3.0.0&sdki=8000405&vi…BlzmDUsTXBBNCV3-nGEmf7j2xxymfF89RPr4pww&ref=https%3A%2F%2Fswimmadev.xyz%2F Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://pagead2.googlesyndication.com/pagead/gen_204?rt=adsense&ec=6&lid=18&id&c=1708006551060480&domain=swimmadev.xyz Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by JefferysTuber** [comment]
angular version: Object {full: "1.4.7", major: 1, minor: 4, dot: 7, codeName: "dark-luminescence"}

**Comment by localyost3000** [comment]
Its this `Chrome 46.0.2490.71 m`.  This new version comes with an "auto-block background autoplaying media" feature, which kinda leaves us dead in the water.

This is now super high-priority, and I have no idea where to start

**Comment by localyost3000** [comment]
Shoutout to @MhackerX for fixing this!
