### ISSUE TITLE
After a while the currently playing song & volume controls disappear.

### ISSUE THREAD

**Issue by Reanmachine** [swimmadude66/YTRadio#37]
I don't know what triggers it, but after some time the controls disappear and i can no longer mute/unmute/change volume.

![See!](http://i.imgur.com/8lhyqEB.png)

**Comment by localyost3000** [comment]
This looks to be an error stemming from the fix to chrome autoplay. The "playing" flag is not being set correctly, and its causing this. It happens seemingly randomly, and goes away on refresh, so this will be a hard one to track down.

**Comment by localyost3000** [comment]
Fixed in commit 4924f11886c6c51d8048257d384d812d6589a972
