### ISSUE TITLE
When sending the song from the top of a playlist to the bottom, the playlist breaks.

### ISSUE THREAD

**Issue by DavidErvin** [swimmadude66/YTRadio#57]
Using the down arrow button to send the top song in my playlist to the bottom, the playlist freezes.  I can no longer move any songs around, the active playlist can't be changed, and scrolling to the bottom of the playlist shows a track with no thumbnail, no title, and all three buttons still on it (see screencap)
![screen shot 2017-03-14 at 11 36 54 am](https://cloud.githubusercontent.com/assets/14335260/23908482/8b1315e2-08aa-11e7-8f1a-3b3aec92c3ae.png)

**Comment by DavidErvin** [comment]
Actually... when this happens the whole UI stops working with the exception of scrolling the current playlist.

**Comment by DavidErvin** [comment]
And I can replicate it for moving a track to the top of the playlist too.
![screen shot 2017-03-14 at 11 40 33 am](https://cloud.githubusercontent.com/assets/14335260/23908688/14b46440-08ab-11e7-8cc6-ff5b8745c9a8.png)

**Comment by localyost3000** [comment]
WHOOPS. Needed to pass the actual index of the song, not a meaningless pointer....
