### ISSUE TITLE
If the screen is narrow, layout of playlists is b0rked

### ISSUE THREAD

**Issue by DavidErvin** [swimmadude66/YTRadio#60]
<img width="1125" alt="screen shot 2017-03-14 at 3 58 19 pm" src="https://cloud.githubusercontent.com/assets/14335260/23919946/28106862-08cf-11e7-90d8-fd491f28c5c7.png">

**Comment by localyost3000** [comment]
Fixed in commit 28951a2b3412466537082d6a3906bbc50b1d4b0a

My wife had a good idea for how to handle playlist names in responsive view, but its gonna take a while
